services:
  accumulator:
    build:
      context: .
      dockerfile: src/OrderAccumulator/Dockerfile
    container_name: accumulator
    ports:
      - "5001:5001"

  generator:
    build:
      context: .
      dockerfile: src/OrderGenerator.Api/Dockerfile
    container_name: generator
    ports:
      - "8080:8080"
    depends_on:
      - accumulator
    environment:
      - ASPNETCORE_URLS=http://+:8080

  frontend:
    build:
      context: src/OrderGenerator.Frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - generator